# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverages', '0003_metadata_items_semantic'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='axis_1_reference_type',
            field=models.SmallIntegerField(choices=[(0, b'regular'), (1, b'irregular'), (2, b'displaced'), (3, b'other')], default=0),
        ),
        migrations.AddField(
            model_name='grid',
            name='axis_2_reference_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, b'regular'), (1, b'irregular'), (2, b'displaced'), (3, b'other')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='grid',
            name='axis_3_reference_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, b'regular'), (1, b'irregular'), (2, b'displaced'), (3, b'other')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='grid',
            name='axis_4_reference_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, b'regular'), (1, b'irregular'), (2, b'displaced'), (3, b'other')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grid',
            name='axis_1_type',
            field=models.SmallIntegerField(choices=[(0, b'spatial'), (1, b'elevation'), (2, b'temporal'), (3, b'index'), (4, b'other')]),
        ),
        migrations.AlterField(
            model_name='grid',
            name='axis_2_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, b'spatial'), (1, b'elevation'), (2, b'temporal'), (3, b'index'), (4, b'other')], null=True),
        ),
        migrations.AlterField(
            model_name='grid',
            name='axis_3_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, b'spatial'), (1, b'elevation'), (2, b'temporal'), (3, b'index'), (4, b'other')], null=True),
        ),
        migrations.AlterField(
            model_name='grid',
            name='axis_4_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, b'spatial'), (1, b'elevation'), (2, b'temporal'), (3, b'index'), (4, b'other')], null=True),
        ),
    ]
