# Generated by Django 2.2.17 on 2022-03-15 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coverages', '0008_incidence_angle'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='eoobject',
            index_together={('begin_time', 'end_time')},
        ),
    ]
