# Generated by Django 5.2 on 2025-04-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverages', '0014_rename_eoobject_begin_time_end_time_coverages_e_begin_t_3d6a5d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandstatistics',
            name='histogram',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
