# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coverages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceVisibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[(b'wms', b'WMS'), (b'wcs', b'WCS'), (b'os', b'OpenSearch')], max_length=4)),
                ('visibility', models.BooleanField(default=True)),
                ('eo_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_visibility', to='coverages.EOObject')),
            ],
        ),
    ]
