# Generated by Django 5.2 on 2025-04-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_name_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicevisibility',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
