# Generated by Django 2.2.17 on 2021-02-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webclient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='histogram_bin_count',
            field=models.IntegerField(default=28),
        ),
        migrations.AddField(
            model_name='extra',
            name='histogram_threshold',
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name='extra',
            name='load_more',
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name='extra',
            name='max_zoom',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='extra',
            name='search_limit',
            field=models.IntegerField(default=600),
        ),
    ]
