# Generated by Django 5.2 on 2025-04-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webclient', '0002_extra_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
