# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='instance',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='processes.Instance'),
        ),
        migrations.AlterField(
            model_name='response',
            name='instance',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='processes.Instance'),
        ),
    ]
