# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-21 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024)),
                ('storage_auth_type', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=1024, null=True, unique=True)),
                ('auth_parameters', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='storage',
            name='storage_auth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backends.StorageAuth'),
        ),
    ]
