# Generated by Django 3.2.18 on 2023-04-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0003_nameblank'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='streaming',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
