name: build
on:
  push:
    paths:
      - '.github/workflows/tests.yaml'
      - 'setup.py'
      - 'setup.cfg'
      - 'MANIFEST.in'
      - 'pyproject.toml'
      - 'eoxserver/**'
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the eoxserver docker image
        run: |
          docker build -t eoxserver .
