name: CI
on:
  push:
    paths:
      - '.github/workflows/**'
      - 'setup.py'
      - 'setup.cfg'
      - 'MANIFEST.in'
      - 'pyproject.toml'
      - 'eoxserver/**'
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the eoxserver docker image
        run: |
          docker build -t eoxserver .
          docker save eoxserver | gzip > eoxserver.tar.gz
      - uses: actions/upload-artifact@v3
        with:
          name: eoxserver
          path: eoxserver.tar.gz
          retention-days: 2

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - db: postgis
          python_bin: python3
        - db: spatialite
          python_bin: python3
    needs: build-docker
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3.0.1
        with:
          name: eoxserver
      - name: Import docker image
        run: |
          docker load --input eoxserver.tar.gz
      - name: Run the tests
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: |
          echo "DB=${{ matrix.db }}" >> sample.env
          docker-compose config
          docker-compose up -d
          docker-compose ps
          docker exec -i eoxserver_autotest_1 pip3 install scipy
          docker exec -i eoxserver_autotest_1 ${{ matrix.python_bin }} -m eoxserver.services.ows.wps.test_data_types
          docker exec -i eoxserver_autotest_1 ${{ matrix.python_bin }} -m eoxserver.services.ows.wps.test_allowed_values
          docker exec -i eoxserver_autotest_1 ${{ matrix.python_bin }} manage.py test --pythonpath=./eoxserver/ eoxserver.core -v2
          docker exec -i eoxserver_autotest_1 ${{ matrix.python_bin }} manage.py test --pythonpath=./eoxserver/ eoxserver.backends -v2
          docker exec -i eoxserver_autotest_1 ${{ matrix.python_bin }} manage.py test --pythonpath=./eoxserver/ eoxserver.services -v2
          docker exec -i eoxserver_autotest_1 ${{ matrix.python_bin }} manage.py test --pythonpath=./eoxserver/ eoxserver.resources.coverages -v2
          docker exec -i eoxserver_autotest_1 ${{ matrix.python_bin }} manage.py test autotest_services --tag wcs20 -v2
          docker exec -i eoxserver_autotest_1 ${{ matrix.python_bin }} manage.py test autotest_services --tag wcs11 -v2
          docker exec -i eoxserver_autotest_1 ${{ matrix.python_bin }} manage.py test autotest_services --tag wcs10 -v2
          docker exec -i eoxserver_autotest_1 ${{ matrix.python_bin }} manage.py test autotest_services --tag wms -v2
          docker exec -i eoxserver_autotest_1 ${{ matrix.python_bin }} manage.py test autotest_services --tag wps -v2
          docker exec -i eoxserver_autotest_1 ${{ matrix.python_bin }} manage.py test autotest_services --tag opensearch -v2
      - name: Upload logs and outputs of failed tests
        uses: 'actions/upload-artifact@v2'
        with:
          name: logs ${{ matrix.python }} ${{ matrix.db }} ${{ matrix.django }}
          path: |
            autotest/autotest/logs/*.log
            autotest/autotest/responses/*
          retention-days: 5
        if: failure()

  publish-docker:
    runs-on: ubuntu-latest
    needs: build-docker 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3.0.1
        with:
          name: eoxserver
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_TAG::$([[ $GITHUB_REF == refs/tags/* ]] && echo ${GITHUB_REF#refs/tags/} || echo "")
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: success()
      - name: Import docker image
        run: |
          docker load --input eoxserver.tar.gz
      - name: Tag docker latest image
        run: |
          docker tag eoxserver eoxa/eoxserver:latest
        if: github.ref == 'refs/heads/master'
      - name: Tag docker release image
        run: |
          docker tag eoxserver eoxa/eoxserver:${{ steps.branch_name.outputs.SOURCE_TAG }}
        if: success() && steps.branch_name.outputs.SOURCE_TAG
      - name: Push docker images
        run: |
          # TODO: --all-tags does not seem to work with the version on github-actions
          # docker push --all-tags eoxa/eoxserver
          for tag in $(docker image ls --format "{{.Tag}}" eoxa/eoxserver) ; do docker push "eoxa/eoxserver:$tag" ; done
        if: success()

  publish-pypi:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_TAG::$([[ $GITHUB_REF == refs/tags/* ]] && echo ${GITHUB_REF#refs/tags/} || echo "")
        with:
          name: eoxserver-dist
      - name: Build Python package
        id: build_python_release
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          python setup.py sdist bdist_wheel
          echo ::set-output name=WHEEL_FILE::$(ls dist/*.whl)
          echo ::set-output name=SRC_DIST_FILE::$(ls dist/*.tar.gz)  
      - name: Push package to pypi
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
        if: success()
  
  release:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_TAG::$([[ $GITHUB_REF == refs/tags/* ]] && echo ${GITHUB_REF#refs/tags/} || echo "")
      - name: Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ steps.branch_name.outputs.SOURCE_TAG }}
          draft: true
      - name: Upload Release Asset Wheel
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.build_python_release.outputs.WHEEL_FILE }}
          asset_name: ${{ steps.build_python_release.outputs.WHEEL_FILE }}
          asset_content_type: application/x-wheel+zip
        if: success()
      - name: Upload Release Asset Source Dist
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ${{ steps.build_python_release.outputs.SRC_DIST_FILE }}
          asset_name: ${{ steps.build_python_release.outputs.SRC_DIST_FILE }}
          asset_content_type: application/tar+gzip
        if: success()
  
  notify:
    runs-on: ubuntu-20.04
    needs: release
    steps:
      - name: action-slack
        uses: 8398a7/action-slack@v3.8.0
        with:
          status: ${{ needs.run.result }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
