name: tests
on: 
  push:
    paths:
      - '.github/workflows/tests.yaml'
      - 'setup.py'
      - 'setup.cfg'
      - 'MANIFEST.in'
      - 'pyproject.toml'
      - 'eoxserver/**'
  pull_request:
    branches: [master]
    paths:
      - '.github/workflows/tests.yaml'
      - 'setup.py'
      - 'setup.cfg'
      - 'MANIFEST.in'
      - 'pyproject.toml'
      - 'eoxserver/**'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - db: postgis
          python_bin: python3
        - db: spatialite
          python_bin: python3
    steps:
      - uses: actions/checkout@v2
      - name: Build the eoxserver docker image
        run: |
          docker build -t eoxserver .
      - name: Run the tests
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: |
          echo "DB=${{ matrix.db }}" >> sample.env
          docker-compose config
          docker-compose up -d
          docker-compose ps
          docker exec -i eoxserver_autotest_1 pip3 install scipy
          docker exec -i eoxserver_autotest_1 ${{ matrix.python_bin }} -m eoxserver.services.ows.wps.test_data_types
          docker exec -i eoxserver_autotest_1 ${{ matrix.python_bin }} -m eoxserver.services.ows.wps.test_allowed_values
          docker exec -i eoxserver_autotest_1 ${{ matrix.python_bin }} manage.py test --pythonpath=./eoxserver/ eoxserver.core -v2
          docker exec -i eoxserver_autotest_1 ${{ matrix.python_bin }} manage.py test --pythonpath=./eoxserver/ eoxserver.backends -v2
          docker exec -i eoxserver_autotest_1 ${{ matrix.python_bin }} manage.py test --pythonpath=./eoxserver/ eoxserver.services -v2
          docker exec -i eoxserver_autotest_1 ${{ matrix.python_bin }} manage.py test --pythonpath=./eoxserver/ eoxserver.resources.coverages -v2
          docker exec -i eoxserver_autotest_1 ${{ matrix.python_bin }} manage.py test autotest_services --tag wcs20 -v2
          docker exec -i eoxserver_autotest_1 ${{ matrix.python_bin }} manage.py test autotest_services --tag wcs11 -v2
          docker exec -i eoxserver_autotest_1 ${{ matrix.python_bin }} manage.py test autotest_services --tag wcs10 -v2
          docker exec -i eoxserver_autotest_1 ${{ matrix.python_bin }} manage.py test autotest_services --tag wms -v2
          docker exec -i eoxserver_autotest_1 ${{ matrix.python_bin }} manage.py test autotest_services --tag wps -v2
          docker exec -i eoxserver_autotest_1 ${{ matrix.python_bin }} manage.py test autotest_services --tag opensearch -v2
      - name: Upload logs and outputs of failed tests
        uses: 'actions/upload-artifact@v2'
        with:
          name: logs ${{ matrix.python }} ${{ matrix.db }} ${{ matrix.django }}
          path: |
            autotest/autotest/logs/*.log
            autotest/autotest/responses/*
          retention-days: 5
        if: failure()
